//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryAsnOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryAsnOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryAsnOrder", typeof(qryAsnOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spd_whar1.
        /// </summary>
        internal static string deleteAsnOrder {
            get {
                return ResourceManager.GetString("deleteAsnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spd_whar2.
        /// </summary>
        internal static string deleteAsnOrderDetail {
            get {
                return ResourceManager.GetString("deleteAsnOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_whar1.
        /// </summary>
        internal static string insertAsnOrder {
            get {
                return ResourceManager.GetString("insertAsnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_whar2.
        /// </summary>
        internal static string insertAsnOrderDetail {
            get {
                return ResourceManager.GetString("insertAsnOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whar1 WHERE TrxNo = @TrxNo.
        /// </summary>
        internal static string selectAsnOrder {
            get {
                return ResourceManager.GetString("selectAsnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whar2 WHERE TrxNo = @TrxNo AND LineItemNo = @LineItemNo.
        /// </summary>
        internal static string selectAsnOrderDetail {
            get {
                return ResourceManager.GetString("selectAsnOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whar2 WHERE TrxNo = @TrxNo.
        /// </summary>
        internal static string selectAsnOrderDetails {
            get {
                return ResourceManager.GetString("selectAsnOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @AsnOrderMth varchar(20) = CONVERT(CHAR(4), @AsnOrderDate, 12)
        ///DECLARE @LastSeqNo int;
        ///DECLARE @NewAsnOrderNo nvarchar(20);
        ///
        ///SELECT @LastSeqNo = ISNULL(MAX(CONVERT(INT,RIGHT(AsnOrderNo,5))),0)
        ///FROM whar1 
        ///WHERE SUBSTRING(AsnOrderNo,4,4) = CONVERT(CHAR(4), @AsnOrderDate, 12)
        ///
        ///SET @LastSeqNo = @LastSeqNo + 1;
        ///SET @NewAsnOrderNo = &apos;ASN&apos; + @AsnOrderMth + RIGHT(&apos;00000&apos; + CONVERT(VARCHAR,@LastSeqNo),5);
        ///SELECT @NewAsnOrderNo.
        /// </summary>
        internal static string selectNewAsnOrderNo {
            get {
                return ResourceManager.GetString("selectNewAsnOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 BusinessPartyName FROM rfbp1 WHERE BusinessPartyCode = @BusinessPartyCode.
        /// </summary>
        internal static string selectSupplierName {
            get {
                return ResourceManager.GetString("selectSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 WarehouseName FROM whwh1 WHERE WarehouseCode = @WarehouseCode.
        /// </summary>
        internal static string selectWarehouseName {
            get {
                return ResourceManager.GetString("selectWarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whar2 WHERE TrxNo = @TrxNo.
        /// </summary>
        internal static string selectwhar2 {
            get {
                return ResourceManager.GetString("selectwhar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM whar2 WHERE TrxNo = @TrxNo AND LineItemNo = @LineItemNo.
        /// </summary>
        internal static string selectWhar2Count {
            get {
                return ResourceManager.GetString("selectWhar2Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_whar1.
        /// </summary>
        internal static string updateAsnOrder {
            get {
                return ResourceManager.GetString("updateAsnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_whar2.
        /// </summary>
        internal static string updateAsnOrderDetail {
            get {
                return ResourceManager.GetString("updateAsnOrderDetail", resourceCulture);
            }
        }
    }
}
