//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryBusinessParty {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryBusinessParty() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryBusinessParty", typeof(qryBusinessParty).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spd_rfbp1.
        /// </summary>
        internal static string deleteBusinessParty {
            get {
                return ResourceManager.GetString("deleteBusinessParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_rfbp1.
        /// </summary>
        internal static string insertBusinessParty {
            get {
                return ResourceManager.GetString("insertBusinessParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM rfbp1 WHERE BusinessPartyCode = @BusinessPartyCode.
        /// </summary>
        internal static string selectBusinessParty {
            get {
                return ResourceManager.GetString("selectBusinessParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM rfbp1 WHERE BusinessPartyCode = @BusinessPartyCode.
        /// </summary>
        internal static string selectBusinessPartyCount {
            get {
                return ResourceManager.GetString("selectBusinessPartyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 CityName FROM rfct1 WHERE CountryCode = &apos;{0}&apos; AND CityCode = &apos;{1}&apos;.
        /// </summary>
        internal static string selectCityName {
            get {
                return ResourceManager.GetString("selectCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 CountryName FROM rfcy1 WHERE CountryCode = &apos;{0}&apos;.
        /// </summary>
        internal static string selectCountryName {
            get {
                return ResourceManager.GetString("selectCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 WarehouseName FROM whwh1 WHERE WarehouseCode = &apos;{0}&apos;.
        /// </summary>
        internal static string selectWarehouseName {
            get {
                return ResourceManager.GetString("selectWarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_rfbp1.
        /// </summary>
        internal static string updateBusinessParty {
            get {
                return ResourceManager.GetString("updateBusinessParty", resourceCulture);
            }
        }
    }
}
