//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryBarCodeItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryBarCodeItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryBarCodeItem", typeof(qryBarCodeItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM whbi2 WHERE TrxNo = @TrxNo AND TablePrefix = @TablePrefix;
        ///DELETE FROM whbi1 WHERE TrxNo = @TrxNo AND TablePrefix = @TablePrefix;.
        /// </summary>
        internal static string DeleteBarcodeItem {
            get {
                return ResourceManager.GetString("DeleteBarcodeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM whbi2 WHERE TrxNo = @TrxNo AND TablePrefix = @TablePrefix AND LineItemNo = @LineItemNo.
        /// </summary>
        internal static string DeleteBarcodeItemDetail {
            get {
                return ResourceManager.GetString("DeleteBarcodeItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[whbi1]
        ///           ([TrxNo]
        ///           ,[TablePrefix]
        ///           ,[CreateBy]
        ///           ,[CreateDateTime])
        ///     VALUES
        ///           (@TrxNo
        ///           ,@TablePrefix
        ///           ,@CreateBy
        ///           ,@CreateDateTime).
        /// </summary>
        internal static string InsertBarcodeItem {
            get {
                return ResourceManager.GetString("InsertBarcodeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[whbi2]
        ///           ([TrxNo]
        ///           ,[TablePrefix]
        ///           ,[LineItemNo]
        ///           ,[ItemCode]
        ///           ,[ItemName]
        ///           ,[DimensionFlag]
        ///           ,[Qty]
        ///           ,[UomCode]
        ///           ,[Length]
        ///           ,[Width]
        ///           ,[Height]
        ///           ,[Weight]
        ///           ,[Volume]
        ///           ,[SpaceArea]
        ///           ,[WorkStation]
        ///           ,[CreateBy]
        ///           ,[CreateDateTime])
        ///     VALUES
        ///           (@TrxNo
        ///           ,@TablePrefix
        ///           ,@Line [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertBarcodeItemDetail {
            get {
                return ResourceManager.GetString("InsertBarcodeItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(LineItemNo),0) + 1 FROM whbi2 WHERE TrxNo = @TrxNo AND TablePrefix = @TablePrefix.
        /// </summary>
        internal static string SelectNewLineItemNo {
            get {
                return ResourceManager.GetString("SelectNewLineItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(TrxNo) FROM whbi1 WHERE TrxNo = @TrxNo AND TablePrefix = @TablePrefix.
        /// </summary>
        internal static string SelectTrxNoCnt {
            get {
                return ResourceManager.GetString("SelectTrxNoCnt", resourceCulture);
            }
        }
    }
}
