//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryGoodsReceiptNote {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryGoodsReceiptNote() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryGoodsReceiptNote", typeof(qryGoodsReceiptNote).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spd_whgr1.
        /// </summary>
        internal static string deleteGrn {
            get {
                return ResourceManager.GetString("deleteGrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spd_whgr2.
        /// </summary>
        internal static string deleteGrnDetail {
            get {
                return ResourceManager.GetString("deleteGrnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_whgr1.
        /// </summary>
        internal static string insertGrn {
            get {
                return ResourceManager.GetString("insertGrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_whgr2.
        /// </summary>
        internal static string insertGrnDetail {
            get {
                return ResourceManager.GetString("insertGrnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sps_AvaliableBinNo.
        /// </summary>
        internal static string selectAvalBinNo {
            get {
                return ResourceManager.GetString("selectAvalBinNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whgr1 WHERE TrxNo = @TrxNo.
        /// </summary>
        internal static string selectGrn {
            get {
                return ResourceManager.GetString("selectGrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whgr2 WHERE TrxNo = @TrxNo AND LineItemNo = @LineItemNo.
        /// </summary>
        internal static string selectGrnDetail {
            get {
                return ResourceManager.GetString("selectGrnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM whgr2 WHERE TrxNo = @TrxNo AND LIneItemNo = @LineItemNo.
        /// </summary>
        internal static string selectGrnDetailCount {
            get {
                return ResourceManager.GetString("selectGrnDetailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whgr2 WHERE TrxNo = @TrxNo ORDER BY LineItemNo.
        /// </summary>
        internal static string selectGrnDetails {
            get {
                return ResourceManager.GetString("selectGrnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @GrnMth varchar(20) = CONVERT(CHAR(4), @ReceiptDate, 12)
        ///DECLARE @LastSeqNo int;
        ///DECLARE @NewGrnNo nvarchar(20);
        ///
        ///SELECT @LastSeqNo = ISNULL(MAX(CONVERT(INT,RIGHT(GoodsReceiptNoteNo,5))),0)
        ///FROM whgr1 
        ///WHERE SUBSTRING(GoodsReceiptNoteNo,4,4) = CONVERT(CHAR(4), @ReceiptDate, 12)
        ///
        ///SET @LastSeqNo = @LastSeqNo + 1;
        ///SET @NewGrnNo = &apos;GRN&apos; + @GrnMth + RIGHT(&apos;00000&apos; + CONVERT(VARCHAR,@LastSeqNo),5);
        ///SELECT @NewGrnNo.
        /// </summary>
        internal static string selectNewGrnNo {
            get {
                return ResourceManager.GetString("selectNewGrnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	gr2.TrxNo,
        ///		gr2.LineItemNo,
        ///		0 AS IsSelected,
        ///		gr1.GoodsReceiptNoteNo,
        ///		gr2.ItemCode,
        ///		gr2.[Description],
        ///		gr2.BinNo,
        ///		gr2.DimensionFlag,
        ///		gr2.UomCode,
        ///		gr2.Qty,
        ///		gr2.[Length],
        ///		gr2.Width,
        ///		gr2.Height,
        ///		gr2.Width,
        ///		gr2.Volume,
        ///		gr2.SpaceArea,
        ///		gr2.ManufactureDate,
        ///		gr2.ExpiryDate
        ///FROM whgr1 gr1 INNER JOIN whgr2 gr2 ON gr1.TrxNo = gr2.TrxNo
        ///WHERE	gr1.StatusCode NOT IN (&apos;CNF&apos;,&apos;DEL&apos;) AND 
        ///		ISNULL(gr2.BinNo,&apos;&apos;) = &apos;&apos; AND
        ///		gr1.WarehouseCode = @WarehouseCode AND
        ///		gr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selectPutAwayItem {
            get {
                return ResourceManager.GetString("selectPutAwayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UserName FROM saus1 WHERE UserId = @UserId.
        /// </summary>
        internal static string selectReceiveByName {
            get {
                return ResourceManager.GetString("selectReceiveByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT StatusCode FROM whgr1 WHERE TrxNo = @TrxNo.
        /// </summary>
        internal static string selectStatusCode {
            get {
                return ResourceManager.GetString("selectStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 BusinessPartyName FROM rfbp1 WHERE BusinessPartyCode = @BusinessPartyCode.
        /// </summary>
        internal static string selectSupplierName {
            get {
                return ResourceManager.GetString("selectSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 WarehouseName FROM whwh1 WHERE WarehouseCode = @WarehouseCode.
        /// </summary>
        internal static string selectWarehouseName {
            get {
                return ResourceManager.GetString("selectWarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE whgr2 SET BinNo = @BinNo WHERE TrxNo = @TrxNo AND LineItemNo = @LineItemNo;
        ///UPDATE whgr1 SET UpdateBy = @UpdateBy, UpdateDateTime = GETDATE() WHERE TrxNo = @TrxNo;.
        /// </summary>
        internal static string updateBinNo {
            get {
                return ResourceManager.GetString("updateBinNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_whgr1.
        /// </summary>
        internal static string updateGrn {
            get {
                return ResourceManager.GetString("updateGrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_whgr2.
        /// </summary>
        internal static string updateGrnDetail {
            get {
                return ResourceManager.GetString("updateGrnDetail", resourceCulture);
            }
        }
    }
}
