//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryItem", typeof(qryItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spd_whit1.
        /// </summary>
        internal static string deleteItem {
            get {
                return ResourceManager.GetString("deleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_whit1.
        /// </summary>
        internal static string insertItem {
            get {
                return ResourceManager.GetString("insertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CountryName FROM rfcy1 WHERE CountryCode = @CountryCode.
        /// </summary>
        internal static string selectCountryName {
            get {
                return ResourceManager.GetString("selectCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whit1 WHERE ItemCode = @ItemCode.
        /// </summary>
        internal static string selectItem {
            get {
                return ResourceManager.GetString("selectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 * FROM whit1 WHERE ItemRefNo = @ItemRefNo.
        /// </summary>
        internal static string selectItemByItemRefNo {
            get {
                return ResourceManager.GetString("selectItemByItemRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Description FROM whic1 WHERE ItemClassCode = @ItemClassCode.
        /// </summary>
        internal static string selectItemClassDesc {
            get {
                return ResourceManager.GetString("selectItemClassDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM whit1 WHERE ItemCode = @ItemCode.
        /// </summary>
        internal static string selectItemCount {
            get {
                return ResourceManager.GetString("selectItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT BusinessPartyName FROM rfbp1 WHERE BusinessPartyCode = @BusinessPartyCode.
        /// </summary>
        internal static string selectSupplierName {
            get {
                return ResourceManager.GetString("selectSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_whit1.
        /// </summary>
        internal static string updateItem {
            get {
                return ResourceManager.GetString("updateItem", resourceCulture);
            }
        }
    }
}
