//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryPutAway {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryPutAway() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryPutAway", typeof(qryPutAway).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	gr2.TrxNo,
        ///		gr2.LineItemNo,
        ///		0 AS IsSelected,
        ///		gr1.GoodsReceiptNoteNo,
        ///		gr2.ItemCode,
        ///		gr2.[Description],
        ///		gr2.BinNo,
        ///		gr2.DimensionFlag,
        ///		gr2.UomCode,
        ///		gr2.Qty,
        ///		gr2.[Length],
        ///		gr2.Width,
        ///		gr2.Height,
        ///		gr2.Width,
        ///		gr2.Volume,
        ///		gr2.SpaceArea,
        ///		gr2.ManufactureDate,
        ///		gr2.ExpiryDate
        ///FROM whgr1 gr1 INNER JOIN whgr2 gr2 ON gr1.TrxNo = gr2.TrxNo
        ///WHERE	gr1.StatusCode NOT IN (&apos;CNF&apos;,&apos;DEL&apos;) AND 
        ///		ISNULL(gr2.BinNo,&apos;&apos;) = &apos;&apos; AND
        ///		gr1.WarehouseCode = @WarehouseCode AND
        ///		gr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selectItems {
            get {
                return ResourceManager.GetString("selectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE whgr2 SET BinNo = @BinNo WHERE TrxNo = @TrxNo AND LineItemNo = @LineItemNo;
        ///UPDATE whiv1 SET BinNo = @BinNo, UpdateBy = @UpdateBy, UpdateDateTime = GETDATE() WHERE BatchNo = @BatchNo AND BatchLineItemNo = @BatchLineItemNo;
        ///UPDATE whgr1 SET UpdateBy = @UpdateBy, UpdateDateTime = GETDATE() WHERE TrxNo = @TrxNo;.
        /// </summary>
        internal static string updateBinNo {
            get {
                return ResourceManager.GetString("updateBinNo", resourceCulture);
            }
        }
    }
}
