//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryStorageSpaceEnq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryStorageSpaceEnq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryStorageSpaceEnq", typeof(qryStorageSpaceEnq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	wh2.BinNo,
        ///		wh2.[Length],
        ///		wh2.Width,
        ///		wh2.Height,
        ///		wh2.PalletSpace,
        ///		wh2.StoreSpace,
        ///		iv.UsedStoreSpace,
        ///		ISNULL(wh2.StoreSpace - iv.UsedStoreSpace,0) AS [BalanceStoreSpace]
        ///FROM whwh2 wh2 
        ///	OUTER APPLY (
        ///		SELECT ISNULL(SUM(iv1.SpaceArea),0) AS [UsedStoreSpace] 
        ///		FROM whiv1 iv1 
        ///		WHERE	iv1.StatusCode != &apos;DEL&apos; AND
        ///				iv1.WarehouseCode = wh2.WarehouseCode AND
        ///				iv1.BinNo = wh2.BinNo AND
        ///				iv1.CreateDateTime BETWEEN @FromDate AND @ToDate
        ///	) iv
        ///WHERE wh2.WarehouseCode = @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selectBinList {
            get {
                return ResourceManager.GetString("selectBinList", resourceCulture);
            }
        }
    }
}
