//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warenet.WebApi.QuerySource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class qryWarehouse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal qryWarehouse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warenet.WebApi.QuerySource.qryWarehouse", typeof(qryWarehouse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spd_whwh1.
        /// </summary>
        internal static string deletewhwh1 {
            get {
                return ResourceManager.GetString("deletewhwh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM whwh2 WHERE WarehouseCode = @WarehouseCode.
        /// </summary>
        internal static string deletewhwh2 {
            get {
                return ResourceManager.GetString("deletewhwh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_whwh1.
        /// </summary>
        internal static string insertwhwh1 {
            get {
                return ResourceManager.GetString("insertwhwh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spi_whwh2.
        /// </summary>
        internal static string insertwhwh2 {
            get {
                return ResourceManager.GetString("insertwhwh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 CityName FROM rfct1 WHERE CountryCode = @CountryCode AND CityCode = @CityCode.
        /// </summary>
        internal static string selectCityName {
            get {
                return ResourceManager.GetString("selectCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 CountryName FROM rfcy1 WHERE CountryCode = @CountryCode.
        /// </summary>
        internal static string selectCountryName {
            get {
                return ResourceManager.GetString("selectCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT StoreTypeDesc FROM whst1 WHERE StoreTypeCode = @StoreTypeCode.
        /// </summary>
        internal static string selectStoreTypeDesc {
            get {
                return ResourceManager.GetString("selectStoreTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM whwh1 WHERE WarehouseCode = @WarehouseCode.
        /// </summary>
        internal static string selectWhCount {
            get {
                return ResourceManager.GetString("selectWhCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whwh2 WHERE UseFlag = &apos;Y&apos; AND [WarehouseCode] = @WarehouseCode AND BinNo = @BinNo.
        /// </summary>
        internal static string selectWhDetail {
            get {
                return ResourceManager.GetString("selectWhDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whwh1 WHERE WarehouseCode = @WarehouseCode.
        /// </summary>
        internal static string selectwhwh1 {
            get {
                return ResourceManager.GetString("selectwhwh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM whwh2 WHERE [WarehouseCode] = @WarehouseCode ORDER BY LineItemNo.
        /// </summary>
        internal static string selectwhwh2 {
            get {
                return ResourceManager.GetString("selectwhwh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_whwh1.
        /// </summary>
        internal static string updatewhwh1 {
            get {
                return ResourceManager.GetString("updatewhwh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spu_whwh2.
        /// </summary>
        internal static string updatewhwh2 {
            get {
                return ResourceManager.GetString("updatewhwh2", resourceCulture);
            }
        }
    }
}
